---
services:
  devcontainer:
    image: golang:1.24.3
    volumes:
      - .:/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOST: "host.docker.internal"
