---
name: Docker
on:
  pull_request:
    types:
      - unlabeled # if GitHub Actions stuck, add and remove "not ready" label to force rebuild
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  schedule:
    - cron: "12 0 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'not ready')

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Initialize Docker Buildx builder
        working-directory: opendocdb-cts
        run: make docker-init

      - name: Build local Docker image
        working-directory: opendocdb-cts
        run: make docker-local

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the latest Docker image
        working-directory: opendocdb-cts
        if: github.event_name == 'push'
        run: >
          docker buildx build --builder=opendocdb-cts --platform=linux/amd64,linux/arm64
          --tag=ghcr.io/opendocdb/cts:latest --push ..
