---
name: Docker
on:
  pull_request:
    types:
      - unlabeled # if GitHub Actions stuck, add and remove "not ready" label to force rebuild
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  schedule:
    - cron: "12 0 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'not ready')

    permissions: {}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Initialize Docker Buildx builder
        working-directory: opendocdb-cts
        run: make docker-init

      - name: Build local Docker image
        working-directory: opendocdb-cts
        run: make docker-local
